# Generated by Django 2.2.9 on 2020-01-10 16:42

import api.models
from django.conf import settings
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]
    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='GidaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('image', models.TextField(default='https://res.cloudinary.com/systemshiftio/image/upload/v1565557753/cloudinary_qyi649.jpg', null=True)),
                ('verified', models.BooleanField(default=False)),
                ('dob', models.DateField(null=True)),
                ('phone', models.CharField(max_length=11, null=True, unique=True)),
                ('star_rating', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BookedApartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Serviced', 'Serviced'), ('Shared', 'Shared'), ('Private', 'Private')], max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('images', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('ammenities', django.contrib.postgres.fields.hstore.HStoreField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('star_rating', models.IntegerField(default=0)),
                ('number_of_checkins', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('', ''), ('Lagos', 'Lagos')], max_length=50)),
                ('country', models.CharField(choices=[('', ''), ('Nigeria', 'Nigeria')], max_length=50)),
                ('location', models.CharField(choices=[('Yaba', 'Yaba'), ('Lekki', 'Lekki'), ('Victoria-Island', 'Victoria-Island'), ('Surulere', 'Surulere'), ('Ikoyi', 'Ikoyi')], max_length=50)),
                ('info', models.TextField(null=True)),
                ('occupied', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
