# Generated by Django 2.2.9 on 2020-01-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200111_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='frequency',
            field=models.CharField(default='Monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='bookedapartment',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Apartment'),
        ),
        migrations.AddField(
            model_name='bookedapartment',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookedapartment',
            name='check_out',
            field=models.DateField(null=True),
        ),
    ]
