# Generated by Django 2.2.9 on 2020-01-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200112_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='occupied',
        ),
    ]
