# Generated by Django 2.2.9 on 2020-01-14 01:51

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi', models.IntegerField()),
                ('investment_time', models.IntegerField(default=6)),
                ('description', models.TextField()),
                ('images', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('state', models.CharField(choices=[('Abuja', 'Abuja'), ('Lagos', 'Lagos')], max_length=50)),
                ('location', models.CharField(choices=[('Yaba', 'Yaba'), ('Lekki', 'Lekki'), ('Victoria-Island', 'Victoria-Island'), ('Surulere', 'Surulere'), ('Ikoyi', 'Ikoyi')], max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('maturity_period', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.Apartment')),
                ('owner', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
